int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int m);
int _isalpha(int m);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
void time_table(void);
int add(int, int);
int print_to_98(int n);
void print_time_table(int n);
